name: kokoro_tts_flutter_example
description: "Kokoro TTS Flutter Example"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  kokoro_tts_flutter: ^0.1.2-exp
  just_audio: ^0.10.3
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/